Repository jfrog/jfrog-cli-artifactory, pull requests merged in 2025-09, with the labels that each got.

#146 Ignore errors in NuGet cleanup command to prevent breaking nuget flow
  artifactory/commands/dotnet/dotnetcommand.go
Labels: improvement, safe to test

#149 Updated dependency in go.mod
  go.mod
  go.sum
Labels: ignore for release, safe to test

#140 Added flexpack build info support for poetry
  artifactory/commands/python/poetry.go
  go.mod
  go.sum
Labels: new feature

#153 Updated 'vscodeextensions' to 'aieditorextensions' for VSCode config
  artifactory/cli/ide/common.go
  artifactory/cli/ide/descriptions.go
  artifactory/cli/ide/vscode/cli.go
  artifactory/commands/ide/vscode/vscode_test.go
Labels: improvement

#158 Go setup - Remove direct suffix go setup
  artifactory/commands/setup/setup.go
Labels: improvement, safe to test

#161 Setup command - Add gradle publish support
  artifactory/commands/gradle/gradle.go
  artifactory/commands/gradle/gradle_test.go
  artifactory/commands/gradle/resources/jfrog.init.gradle
  artifactory/commands/setup/setup.go
Labels: improvement, safe to test

#166 Improve Setup Go tests cleanup
  artifactory/commands/setup/setup_test.go
Labels: ignore for release, safe to test

#167 Update dependency replace directives to latest versions
  go.mod
  go.sum
Labels: ignore for release, safe to test

#260 add timestamp as props for twine
  artifactory/commands/python/twine.go
Labels: bug, safe to test
