Repository jfrog/jfrog-cli-artifactory, pull requests merged in 2025-04, with the labels that each got.

#60 Fix setup docker message log
  artifactory/commands/setup/setup.go
Labels: bug

#55 Allow Build Publish with `overwrite` Flag When Build Number is New
  artifactory/commands/buildinfo/publish.go
Labels: bug

#65 Upgrade jfrog-cli-artifactory to 0.2.2
  go.mod
  go.sum
Labels: ignore for release

#61 Support multiple image tags in build-docker-create using image-file
  artifactory/commands/container/buildcreate.go
  artifactory/commands/container/buildcreate_test.go
  go.mod
  go.sum
Labels: safe to test
