Repository jfrog/jfrog-cli-artifactory, pull requests merged in 2025-08, with the labels that each got.

#120 Add stages to release bundle evidence create
  evidence/cli/command_cli.go
  evidence/create/create_base.go
  evidence/create/create_release_bundle.go
  evidence/create/create_release_bundle_test.go
  evidence/intoto/intoto_statement_v1.go
Labels: new feature

#118 Add sigstore bundle verification
  evidence/get/testutils.go
  evidence/model/verify.go
  evidence/verify/evidence_verifier.go
  evidence/verify/evidence_verifier_test.go
  evidence/verify/verifiers/ca/tuf_certificate_provider.go
  evidence/verify/verifiers/dsse_verifier.go
  evidence/verify/verifiers/dsse_verifier_test.go
  evidence/verify/verifiers/evidence_parser.go
  evidence/verify/verifiers/evidence_parser_test.go
  evidence/verify/verifiers/evidence_verifier.go
  evidence/verify/verifiers/evidence_verifier_test.go
  evidence/verify/verifiers/sigstore_verifier.go
  evidence/verify/verifiers/sigstore_verifier_test.go
  evidence/verify/verifiers/test_utils.go
  evidence/verify/verify_base.go
  evidence/verify/verify_base_test.go
Labels: new feature

#112 Add GitHub Actions summary for the create evidence command
  evidence/create/create_base.go
  evidence/create/create_base_test.go
  evidence/create/create_build.go
  evidence/create/create_build_test.go
  evidence/create/create_custom.go
  evidence/create/create_custom_test.go
  evidence/create/create_github.go
  evidence/create/create_github_test.go
  evidence/create/create_package.go
  evidence/create/create_package_test.go
  evidence/create/create_release_bundle.go
  evidence/create/create_release_bundle_test.go
  evidence/model/create.go
  evidence/package.go
  evidence/utils/aql.go
  evidence/utils/environment.go
  evidence/utils/environment_test.go
  evidence/verify/verify_base.go
  go.mod
  go.sum
Labels: new feature

#116 Support multiple envs for rpt
  artifactory/commands/repository/repository_test.go
  artifactory/commands/repository/template.go
Labels: improvement

#124 fix panic on upload evidence in github actions
  evidence/create/create_custom.go
  evidence/create/create_custom_test.go
Labels: bug

#126 Add GetRepositoryPackageType to project setup
  artifactory/commands/setup/setup.go
  artifactory/commands/setup/setup_test.go
Labels: ignore for release

#130 "Upgrade jfrog-cli-artifactory to 0.6.1"
  go.mod
  go.sum
Labels: ignore for release, safe to test

#131 "Upgrade jfrog-cli-artifactory to 0.6.2"
  go.mod
  go.sum
Labels: ignore for release

#129 Add support of docker/oci subject resolution by registry, image name and sha256
  evidence/create/create_custom.go
  evidence/create/create_custom_test.go
  evidence/create/resolvers/aql_resolver.go
  evidence/create/resolvers/oci_resolver.go
  evidence/create/resolvers/oci_resolver_test.go
  evidence/create/resolvers/subject_resolver.go
  evidence/create/resolvers/subject_resolver_test.go
  evidence/sigstore/subject_extractor.go
  evidence/sigstore/subject_extractor_test.go
  go.mod
  go.sum
Labels: new feature

#133 Add sonarqube api for sonar evidence integration
  evidence/cli/command_build.go
  evidence/cli/command_cli.go
  evidence/cli/command_cli_test.go
  evidence/cli/command_custom.go
  evidence/cli/command_github.go
  evidence/cli/command_package.go
  evidence/cli/command_release_bundle.go
  evidence/cli/flags.go
  evidence/config/config.go
  evidence/create/create_base.go
  evidence/create/create_base_test.go
  evidence/create/create_build.go
  evidence/create/create_build_test.go
  evidence/create/create_custom.go
  evidence/create/create_custom_test.go
  evidence/create/create_github.go
  evidence/create/create_package.go
  evidence/create/create_package_test.go
  evidence/create/create_release_bundle.go
  evidence/create/create_release_bundle_test.go
  evidence/intoto/intoto_statement_v1.go
  evidence/intoto/intoto_statement_v1_test.go
  evidence/sonar/client.go
  evidence/sonar/parser.go
  evidence/sonar/parser_test.go
  evidence/sonar/provider.go
  evidence/sonar/provider_test.go
  evidence/sonar/report_detector.go
  evidence/sonar/report_detector_test.go
  evidence/sonar/resolver.go
  evidence/sonar/resolver_test.go
  evidence/sonar/util.go
Labels: new feature

#138 Add markdown report
  evidence/verify/reports/helpers_test.go
  evidence/verify/reports/json_report_printer.go
  evidence/verify/reports/json_report_printer_test.go
  evidence/verify/reports/markdown_report_printer.go
  evidence/verify/reports/markdown_report_printer_test.go
  evidence/verify/reports/plaintext_report_printer.go
  evidence/verify/reports/plaintext_report_printer_test.go
  evidence/verify/reports/report_printer.go
  evidence/verify/reports/utils.go
  evidence/verify/verify_base.go
  evidence/verify/verify_base_test.go
  go.sum
Labels: new feature

#141 Remove fallback logic for Sonar evidence integration and simplify statement building
  evidence/create/create_base.go
  evidence/sonar/client.go
  evidence/sonar/provider.go
  evidence/sonar/provider_test.go
  evidence/sonar/resolver.go
  evidence/sonar/resolver_test.go
Labels: improvement

#132 fixed gradle metadata sources
  artifactory/commands/gradle/resources/jfrog.init.gradle
Labels: bug
