Repository jfrog/jfrog-cli-artifactory, pull requests merged in 2025-07, with the labels that each got.

#91 Add properties for python artifacts
  artifactory/commands/python/twine.go
Labels: bug, safe to test

#89 Added evidence verify command for local verification
  evidence/cli/command.go
  evidence/cli/command_build.go
  evidence/cli/command_cli.go
  evidence/cli/command_cli_test.go
  evidence/cli/command_custom.go
  evidence/cli/command_github.go
  evidence/cli/command_package.go
  evidence/cli/command_relesae_bundle.go
  evidence/cli/docs/verify/help.go
  evidence/cli/flags.go
  evidence/create/create_base.go
  evidence/create/create_base_test.go
  evidence/create/create_build.go
  evidence/create/create_build_test.go
  evidence/create/create_custom.go
  evidence/create/create_github.go
  evidence/create/create_github_test.go
  evidence/create/create_package.go
  evidence/create/create_package_test.go
  evidence/create/create_release_bundle.go
  evidence/create/create_release_bundle_test.go
  evidence/create_package.go
  evidence/cryptox/key_loader.go
  evidence/cryptox/key_loader_test.go
  evidence/cryptox/readkey.go
  evidence/cryptox/utils.go
  evidence/dsse/dsse.go
  evidence/model/evidence_metadata.go
  evidence/model/verify.go
  evidence/package.go
  evidence/package_test.go
  evidence/sign/sign.go
  evidence/sign/sign_test.go
  evidence/utils/aql.go
  evidence/utils/repo_key_builder.go
  evidence/verify/evidence_verifier.go
  evidence/verify/evidence_verifier_test.go
  evidence/verify/verify_base.go
  evidence/verify/verify_base_test.go
  evidence/verify/verify_build.go
  evidence/verify/verify_build_test.go
  evidence/verify/verify_custom.go
  evidence/verify/verify_custom_test.go
  evidence/verify/verify_package.go
  evidence/verify/verify_package_test.go
  evidence/verify/verify_release_bundle.go
  evidence/verify/verify_release_bundle_test.go
  go.mod
Labels: new feature

#103 Updating repoOnly flag description
  cliutils/flagkit/flags.go
  go.mod
  go.sum
Labels: bug

#107 align verify response with evd get command
  evidence/cli/command_cli.go
  evidence/cli/docs/verify/help.go
  evidence/model/verify.go
  evidence/verify/evidence_verifier.go
  evidence/verify/evidence_verifier_test.go
  evidence/verify/verify_base.go
  evidence/verify/verify_base_test.go
  evidence/verify/verify_build_test.go
  evidence/verify/verify_custom_test.go
  evidence/verify/verify_package_test.go
  evidence/verify/verify_release_bundle_test.go
Labels: improvement

#110 update github.com/go-viper/mapstructure/v2
  go.mod
  go.sum
Labels: improvement

#113 Fixing null values in get evidence output
  evidence/get/get_base.go
  evidence/get/get_release_bundle.go
Labels: bug

#114 fix plural form of evidence word. It should be evidence instead of evidences
  evidence/cli/command.go
  evidence/cli/command_build.go
  evidence/cli/command_cli.go
  evidence/cli/command_cli_test.go
  evidence/cli/command_custom.go
  evidence/cli/command_github.go
  evidence/cli/command_package.go
  evidence/cli/command_release_bundle.go
  evidence/cli/flags.go
  evidence/get/get_release_bundle.go
  evidence/verify/verify_base.go
  evidence/verify/verify_base_test.go
  evidence/verify/verify_build.go
  evidence/verify/verify_build_test.go
  evidence/verify/verify_custom.go
  evidence/verify/verify_custom_test.go
  evidence/verify/verify_package.go
  evidence/verify/verify_package_test.go
  evidence/verify/verify_release_bundle.go
  evidence/verify/verify_release_bundle_test.go
Labels: bug
