Repository jfrog/jfrog-cli-artifactory, pull requests merged in 2025-05, with the labels that each got.

#72 Bug fixes for lifecycle promote and distribution update commands
  distribution/cli/cli.go
  lifecycle/cli.go
  lifecycle/docs/promote/help.go
Labels: bug

#67 Support lifecycle annotate command for release bundle
  cliutils/cmddefs/commands.go
  cliutils/flagkit/flags.go
  go.mod
  go.sum
  lifecycle/cli.go
  lifecycle/commands/annotate.go
  lifecycle/commands/annotate_test.go
  lifecycle/commands/common.go
  lifecycle/commands/common_test.go
  lifecycle/docs/annotate/help.go
Labels: new feature

#82 Upgrade jfrog-cli-artifactory to v0.3.1
  go.mod
  go.sum
Labels: safe to test

#73 Feature/docker validate sha
  artifactory/cli/cli.go
  artifactory/commands/container/containermanagerbase.go
  artifactory/commands/container/push.go
  cliutils/flagkit/flags.go
  go.mod
  go.sum
Labels: safe to test
